### ISSUE TITLE
会社を返すAPI

### ISSUE THREAD

**Issue by hiracky16** [ebc0729/RailApi#15]
記録時などに必要となってくる会社を返すAPIを作る
company_id からその会社を返す機能とarea_id からそのエリアの会社一覧を返す機能が必須となる

**Comment by HiroyukiImura** [comment]
この前新しいAPI考えてたけど、思いつかなかったので
どれかアサインしてくれたらやるよー

**Comment by hiracky16** [comment]
@HiroyukiImura 
ちょうどいまアサインしようとしてたところだった
ではお願い！

**Comment by HiroyukiImura** [comment]
エンドポイントは以下とします。
```
- company_id -> 会社名
  - company/:company_id
- area_id -> エリアに属する会社
  - companies/:area_id
```

**Comment by HiroyukiImura** [comment]
エリアに属する会社のエンドポイントは
```
areas/:area_id/companies
```
の方が自然な気がしたのでそうします。

**Comment by hiracky16** [comment]
対応済みなんでクローズ
