### ISSUE TITLE
develop環境で RailApp から RailApi にリクエストできるように設定する

### ISSUE THREAD

**Issue by hiracky16** [ebc0729/RailApi#29]
RailApp 側から ajax を使って RailAPi にリクエストすると XSS対策からできないようになっていた。
そのため RailApi 側に下記のサイトのような設定を追加し、開発環境で ajax からリクエストできるようにする。

RailsでAccess-Control-Allow-Originを簡単に設定できるrack-cors
https://qiita.com/kaorumori/items/0a53c248343892c8f35c

**Comment by HiroyukiImura** [comment]
上記URLのリンクが切れてる…

**Comment by HiroyukiImura** [comment]
これ割と早めにやったほうが良さそう
この対応をするとしないのとでフロントエンド側のデータ取得部分のコードが大きく変わるはずなので

**Comment by hiracky16** [comment]
一旦必要なさそうなのでクローズ
