### ISSUE TITLE
User API の作成

### ISSUE THREAD

**Issue by hiracky16** [ebc0729/RailApi#37]
- [x] ユーザの作成
- [x] ユーザの取得
- [x] ユーザの更新
- [x] ユーザの削除

それぞれを行うAPIを作成する

**Comment by hiracky16** [comment]
@domi10momo 対応お願いします！

**Comment by hiracky16** [comment]
参考となりそうなURL
- http://clc.gonna.jp/2017/01/post-1306/
- http://uraway.hatenablog.com/entry/2016/07/11/090206

**Comment by domi10momo** [comment]
@hiracky16 
さっきapiに一旦入れたdeviseを消す件だけど
前のコミットに戻ってから新しく作成していくのは駄目？

**Comment by hiracky16** [comment]
@domi10momo 
その手があったね！
大丈夫だと思う

**Comment by domi10momo** [comment]
了解。やっていきます。

**Comment by domi10momo** [comment]
@hiracky16 APIはDBのデータを取得するという認識だけどユーザー作成のAPIというのは何かデータを取得するの？
それとも前のRailAppのsign_upのようにユーザにデータを入力させる？

**Comment by hiracky16** [comment]
@domi10momo 
API は DB と アプリの間にあるイメージでデータの読み出しと書き込みを担う役割がある。
例えば、入力されたユーザのデータを以下のような json で API に送信すると User テーブルに情報を登録するという機能を作るって感じやね。
```
{
  user_name: "domi",
  mail_address: "domi@example.com",
  favorite_route: "長崎電気軌道本線"
}
```

User テーブル

|id|user_name|mail_address|favorite_route|
|:---|:---|:---|:---|
|10|domi|domi@example.com|長崎電気軌道本線|

**Comment by hiracky16** [comment]
@domi10momo 
テストには以下のツールを用いるとできると思うから使い方わからなかったらまた聞いてー
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=ja

**Comment by hiracky16** [comment]
@domi10momo 
今日の mtg から期限を設けることにした。一旦8月4日まで
都合等が悪かったら気軽に延ばせるものだから気軽に言ってー！

**Comment by hiracky16** [comment]
これも終わってる？っぽいので完了。
